#!/bin/bash

echo "-------- RUN TEST [string] ---------"
./runqemu.sh "string"
#echo "-------- RUN TEST [fdopen] ---------"
#./runqemu.sh "fdopen"
echo "-------- RUN TEST [search_hsearch] ---------"
./runqemu.sh "search_hsearch"
echo "-------- RUN TEST [fnmatch] ---------"
./runqemu.sh "fnmatch"
#echo "-------- RUN TEST [fscanf] ---------"
#./runqemu.sh "fscanf"
#echo "-------- RUN TEST [popen] ---------"
#./runqemu.sh "popen"
echo "-------- RUN TEST [socket] ---------"
./runqemu.sh "socket"
#echo "-------- RUN TEST [spawn] ---------"
#./runqemu.sh "spawn"
echo "-------- RUN TEST [qsort] ---------"
./runqemu.sh "qsort"
echo "-------- RUN TEST [time] ---------"
./runqemu.sh "time"
echo "-------- RUN TEST [sscanf] ---------"
./runqemu.sh "sscanf"
echo "-------- RUN TEST [snprintf] ---------"
./runqemu.sh "snprintf"
echo "-------- RUN TEST [swprintf] ---------"
./runqemu.sh "swprintf"
echo "-------- RUN TEST [stat] ---------"
./runqemu.sh "stat"
echo "-------- RUN TEST [strtod] ---------"
./runqemu.sh "strtod"
echo "-------- RUN TEST [strtol] ---------"
./runqemu.sh "strtol"
echo "-------- RUN TEST [ungetc] ---------"
./runqemu.sh "ungetc"
echo "-------- RUN TEST [wcstol] ---------"
./runqemu.sh "wcstol"
echo "-------- RUN TEST [fwscanf] ---------"
./runqemu.sh "fwscanf"
echo "-------- RUN TEST [basename] ---------"
./runqemu.sh "basename"
echo "-------- RUN TEST [dirname] ---------"
./runqemu.sh "dirname"
echo "-------- RUN TEST [memstream] ---------"
./runqemu.sh "memstream"
echo "-------- RUN TEST [mbc] ---------"
./runqemu.sh "mbc"
echo "-------- RUN TEST [setjmp] ---------"
./runqemu.sh "setjmp"
echo "-------- RUN TEST [sem] ---------"
./runqemu.sh "sem"
echo "-------- RUN TEST [pthread] ---------"
./runqemu.sh "pthread"
echo "-------- RUN TEST [random] ---------"
./runqemu.sh "random"
echo "-------- RUN TEST [crypt] ---------"
./runqemu.sh "crypt"
echo "-------- RUN TEST [utime] ---------"
./runqemu.sh "utime"
echo "-------- RUN TEST [wcsstr] ---------"
./runqemu.sh "wcsstr"
echo "-------- RUN TEST [env] ---------"
./runqemu.sh "env"
